version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4444:4444' # Проброс портов для доступа к бэкенду

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '7070:80'
